permissionset 70100 GeneratedPermission
{
    Assignable = true;
    Permissions = tabledata "Collect/Prepaid"=RIMD,
        tabledata "Mandate Comment"=RIMD,
        tabledata "Mandate Header"=RIMD,
        tabledata "Mandate Line"=RIMD,
        tabledata MandateType=RIMD,
        tabledata PortL=RIMD,
        tabledata "Received Through"=RIMD,
        tabledata "SharePoint Attachment"=RIMD,
        tabledata "Shipment Mode"=RIMD,
        tabledata "Shipment Term"=RIMD,
        table "Collect/Prepaid"=X,
        table "Mandate Comment"=X,
        table "Mandate Header"=X,
        table "Mandate Line"=X,
        table MandateType=X,
        table PortL=X,
        table "Received Through"=X,
        table "SharePoint Attachment"=X,
        table "Shipment Mode"=X,
        table "Shipment Term"=X,
        report "Aged Accounts PayableR"=X,
        report "Aged Accounts Receivable1"=X,
        report "Mandate E/L Report"=X,
        report "Mandate E/L Uploader"=X,
        report "Purchase Register_RAMA"=X,
        report "Sales Register_RAMA"=X,
        codeunit "Approval Mgmt.Mandate"=X,
        codeunit Events=X,
        codeunit "Page Mgmt Ext"=X,
        codeunit SharePointHandler=X,
        codeunit "Workflow Event Handling Ext"=X,
        codeunit "Workflow Response Handling Ext"=X,
        codeunit "Workflow Setup Ext"=X,
        page "Mandate E/L Card"=X,
        page "Mandate List"=X,
        page "Mandate Subform"=X,
        page "Mandate Type"=X,
        page "SharePoint Attachment API"=X,
        page "SP Document Attachment Details"=X,
        page "SP. Attachment List Factbox"=X;
}